function nicegraph(fig)
% NICEGRAPH(FIG)
%
% See also SAVEGRAPH

%% Initialization
if nargin==1
	figure(fig);
end

set(gca, ...
	'Box'         , 'off'     , ...
	'TickDir'     , 'out'     , ...
	'TickLength'  , [.02 .02] , ...
	'XMinorTick'  , 'on'      , ...
	'YMinorTick'  , 'on'      , ...
	'YGrid'       , 'on'      , ...
	'XGrid'       , 'on'      , ...
	'XColor'      , [.3 .3 .3], ...
	'YColor'      , [.3 .3 .3], ...
	'FontSize',15,...
	'YDir','normal',...
	'LineWidth'   , 1         );

axis square;
